from setuptools import setup

setup(name='stuffed',
      version='0.0.3',
      description="All your belongings",
      long_description="",
      classifiers=["Development Status :: 1 - Planning",
                   "Environment :: Plugins",
                   "License :: OSI Approved :: Apache Software License",
                   "Programming Language :: Python",
                   "Programming Language :: Python :: 2.7",
                   "Topic :: Utilities"],
      keywords='credit card address phone',
      author='@iopeak',
      author_email='steve@stevepeak.net',
      url='https://github.com/stevepeak/stuffed',
      license='Apache v2',
      packages=['stuffed'],
      include_package_data=True,
      zip_safe=True,
      install_requires=["valideer==0.3",
                        "requests==2.0.0",
                        "timestring==1.4.4",
                        "pytz==2013b"],
      entry_points="")
